### ISSUE TITLE
Installation Instructions?

### ISSUE THREAD

**Issue by bneigher** [fruch/micropython-buzzer#2]
Hello.. I'm trying to install this on my ESP32 and I'm having issues.  My assumption is that we move the `buzzer.py` onto our board and then just use it like:

```python
from buzzer import BuzzerPlayer

buzz = BuzzerPlayer(pin=14)
buzz.from_file("/media/jingle.mid")
# buzz.play_midi("/media/jingle.mid")
```

But nothing is happening.  I think it's because midi is not installed on my board
`from midi import MidiFile`

How are we supposed to install it?  Is it this? https://github.com/cjbarnes18/micropython-midi/blob/master/midi.py 
Not seeing the `read_track` method in there.. 

Appreciate the help!

**Comment by fruch** [comment]
I remember taking the midi and the rtttl code out since it was too big for the ESP8266.

But I can't remember which code it was exactly.

Didn't touch this in quite a while

**Comment by fruch** [comment]
Now I've found it
The midi and rtttl modules were moved to the test directory, you can pick it from there

https://github.com/fruch/micropython-buzzer/blob/master/test/midi.py

**Comment by fruch** [comment]
Would live to see/hear a bit more on what you are building...

**Comment by bneigher** [comment]
Well I tried merging using the midi.py code.. but it looks to error out on my ESP32
<img width="736" alt="image" src="https://user-images.githubusercontent.com/4627728/211239070-1c2ff3f9-5e20-4beb-9aa5-1d50345959bb.png">

I did manager to get midi playing using the following:

```python
import umidiparser
import _thread as th
from machine import Pin, PWM
from time import sleep_us

buzz = PWM(Pin(14))
buzz.duty(0)

def play_tone(freq, usec, duty=512):
    if freq > 0:
        buzz.freq(int(freq)) # Set frequency
        buzz.duty(duty)
        sleep_us(usec)       # Play for a number of usec 
    buzz.duty(0)               # Stop playing for gap between notes

def play_jingle(filename="up.mid", duty=512):
    # map MIDI notes (0-127) to frequencies. Note 69 is 440 Hz ('A4')
    freqs = [440 * 2**((float(x) - 69) / 12) for x in range(128)]

    for event in umidiparser.MidiFile(f"/media/{filename}", reuse_event_object=True).play():
        if event.status == umidiparser.NOTE_ON:
            play_tone(freqs[event.note], event.delta_us, duty)
        elif event.status == umidiparser.NOTE_OFF:
            buzz.duty(0)

def do_jingle(filename="up.mid", duty=512):
    th.start_new_thread(play_jingle, (filename,))

do_jingle("up.mid")
```

though the logic I scoured from a blog post https://scruss.com/blog/2022/08/25/micropython-midi-mayhem-kinda/ (which had a few bugs)... this gets me mostly there :)


What I'm making:
I have a woodworking project similar to https://www.etsy.com/listing/916416912/large-mountain-illuminated-wall-art?show_sold_out_detail=1&ref=nla_listing_details which I am using ESP32 to control the LEDs.  I programmed it to turn on at `X PM` and off at `Y AM`

But I wanted to also have it beep at me when the WiFi has trouble connecting or when it crossing the ON / OFF intervals.. I have little jingles that play on each transition

**Comment by bneigher** [comment]
I would prefer to use this library so that I can rely on your logic for playing the music instead of whatever monstrosity I cobbled together haha.  lmk if you know what the issue I faced is.. happy to try and get ur code running on my ESP32 
https://www.wemos.cc/en/latest/s2/s2_mini.html

**Comment by fruch** [comment]
Can you send me the up.mid file you are using ?

I'll try testing and fixing it

**Comment by bneigher** [comment]
Sure.  I think a better example will be the clock tower song I made, it has examples of rests, and held notes:

**Comment by bneigher** [comment]
[clock_tower_short.mid.zip](https://github.com/fruch/micropython-buzzer/files/10386646/clock_tower_short.mid.zip)

**Comment by fruch** [comment]
@bneigher 

I've found that bug seem like that was a part of the code that was assuming track has notes objects in it, and I turned them into strings in some other place.

now it should be working

**Comment by fruch** [comment]
> @bneigher
> 
> I've found that bug seem like that was a part of the code that was assuming track has notes objects in it, and I turned them into strings in some other place.
> 
> now it should be working

even uploaded a new version to pypi

https://pypi.org/project/micropython-buzzer/1.1.0/

**Comment by bneigher** [comment]
awesome.. I'll give it a whirl when I get back to my esp32

**Comment by bneigher** [comment]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/4627728/212502890-85150630-af03-49fe-9337-76b085b69b1d.png">

It outputs this text but doesn't play anything to pin 14 🤔

**Comment by fruch** [comment]
> <img width="465" alt="image" src="https://user-images.githubusercontent.com/4627728/212502890-85150630-af03-49fe-9337-76b085b69b1d.png">
> 
> It outputs this text but doesn't play anything to pin 14 🤔 

When you use it with Nokia tunes it works ?

I'm guessing the code that uses the PWM doesn't works the same at your board, and you'll need to debug that part

**Comment by bneigher** [comment]
okay just started digging... the first problem (I'm using esp32) is in the tone function... you're only checking if esp8266 and pyboard which for me (esp32) doesn't hit the if or the elif...  

```python
def tone(self, freq, duration=0, duty=30):
        if self.platform == "esp8266"
            print(freq, duration, duty)
            self.buzzer_pin.freq(max(1, int(freq)))
            self.buzzer_pin.duty(duty)
            time.sleep_us( int(duration * 0.9 * 1000) )
            self.buzzer_pin.duty(0)
            time.sleep_us(int(duration * 0.1 * 1000))

        elif self.platform == "pyboard":
            self.timer.freq(freq)  # change frequency for change tone
            self.channel.pulse_width_percent(30)
            self.pyb.delay(duration)

        if callable(self.callback):
            self.callback(freq)
```

Suggested code should follow what you did in the __init__ for that first line:

```python
def tone(self, freq, duration=0, duty=30):
        if "esp" in self.platform:
            print(freq, duration, duty)
           
```


The second issue is that it looks like the freq values being detected are waaayyyy too high..
<img width="478" alt="image" src="https://user-images.githubusercontent.com/4627728/214227787-e84a8d8e-1151-45da-93e4-ed5d38ac7ed0.png">

For me, my [buzzer](https://www.amazon.com/Active-Electric-Buzzer-Arduino-Controller/dp/B06XZYL2QS/ref=asc_df_B06XZYL2QS/?tag=hyprod-20&linkCode=df0&hvadid=312136795426&hvpos=&hvnetw=g&hvrand=6319763143540044489&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9031041&hvtargid=pla-643117061214&psc=1) (pretty standard buzzer) doesn't really make audible sounds at a value of >= `5000` for freq.  Not to mention, 0 is being passed into the tone function which for me results in an error:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/4627728/214228522-240ffbff-64cf-4f1e-8a58-66b47f550121.png">

**Comment by bneigher** [comment]
for me, a successful audible code looks like this for the tone fn:

```python
if "esp" in self.platform:
            self.buzzer_pin.freq(max(1, int(freq * .02)))
            self.buzzer_pin.duty(duty)
            time.sleep_us(int(duration * 0.9 * 1000))
            self.buzzer_pin.duty(0)
            time.sleep_us(int(duration * 0.1 * 1000))
```

I'm taking 2% of the read frequency values and it sounds about right for my device.  Any idea what could be the issue here?  Same song I shared earlier

**Comment by fruch** [comment]
> for me, a successful audible code looks like this for the tone fn:
> 
> ```python
> if "esp" in self.platform:
>             self.buzzer_pin.freq(max(1, int(freq * .02)))
>             self.buzzer_pin.duty(duty)
>             time.sleep_us(int(duration * 0.9 * 1000))
>             self.buzzer_pin.duty(0)
>             time.sleep_us(int(duration * 0.1 * 1000))
> ```
> 
> I'm taking 2% of the read frequency values and it sounds about right for my device.  Any idea what could be the issue here?  Same song I shared earlier

Again I don't remember if I used it with esp32 or not, but it might be reasonable if it needs to be tweaked to fit a different clock rate.

If you do get it working, it the changes on a PR, I might be able to find some time to verify it on esp32 as well.

**Comment by bneigher** [comment]
no worries achi

yea when I get some more time I'll see if there is something about the clock rate.. I'm very new to the micropython world, let alone to micro controllers.. more of a cloud javascript developer by trade.  so idk how helpful I'll be.  would be nice to know what the clock rates are for other boards... perhaps that is the key to calculating the `.02` ratio or whatever is needed as a coefficient to the frequencies getting parsed by your lib.

in the meantime, I've replaced `umidiparser` with your library now that it plays my annoying ass beeps 😄

**Comment by fruch** [comment]
It's lots of trial and error, so your experience is as good as mine here

**Comment by bneigher** [comment]
okay I got it...  
https://github.com/fruch/micropython-buzzer/blob/master/buzzer/__init__.py#L149

transpose is defaulting to 6 in the play_midi function... setting it to 0 means no float magic on the freq values.

I'll make an MR with the two fixes
- generalize esp platform rules (should be the same logic as in the BuzzerPlayer constructor)
- prevent freq values of 0 from being passed to `self.buzzer_pin.freq` calls in the `BuzzerPlayer.tone` method
- change default transpose to 0 in play_midi

**Comment by bneigher** [comment]
I think it would be nice to provide a second argument to `play_midi` (or any other play method) to scale down the duty values.  sometimes a nice soft song is necessary and other times a loud jarring alert sounds may be nice.  but let's call this one a feature request :)
